### ISSUE TITLE
Heroku not triggering

### ISSUE THREAD

**Issue by EllenB** [giswqs/earthengine-apps#3]
Hi Qiusheng,

I am getting the following error when Heroku should be triggered. I followed the lab. Perhaps I am doing something wrong.

I will be happy to test this out further. 

I tried your other repo from your Youtube video [here](https://www.youtube.com/watch?v=nsIjfD83ggA) using this [repo](https://github.com/giswqs/geemap-heroku). I did a git clone on local (not a git fork) and then pushed from local on Heroku and this seemed to build. 

This is the error log I get:
![image](https://user-images.githubusercontent.com/7898589/155553334-d265aff6-b70a-4185-828d-8013136f4492.png)

**Comment by giswqs** [comment]
It appears that Heroku updated the Python versions after I deployed the app. Changing the content of runtime.txt to `python-3.9.10` should resolve the issue. The list of supported Python versions can be found at https://devcenter.heroku.com/articles/python-support#specifying-a-python-version
